export const metadata = {
  title: "React Advanced",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning>Contact Page Me Apka Swagat Hai{children}</body>
    </html>
  );
}
